server:
  port: 8001
  servlet:
    context-path: /gateway
spring:
  application:
    name: zuul
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka